web:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ./hotline:/hotline
        - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
php:
    image: php:7-fpm
    volumes:
        - ./hotline:/hotline