version: '3'

services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: hotline-docker
        ports:
            - 8080:80
        volumes:
            - ./hotline:/hotline
        links:
            - mysql
        environment:
            DB_HOST: mysql
            DB_DATABASE: hotline_docker
            DB_USERNAME: temp_username
            DB_PASSWORD: temp_password
    mysql:
        image: mysql:5.7
        ports:
            - 13306:3306
        environment:
            MYSQL_DATABASE: hotline_docker
            MYSQL_USER: temp_username
            MYSQL_PASSWORD: temp_password
            MYSQL_ROOT_PASSWORD: temp_password